// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnwefdkejobzkszssmge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZud2VmZGtlam9iemtzenNzbWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzY4MjEsImV4cCI6MjA3MDg1MjgyMX0.dzoHmRoFIDH7lkX8Fx8A_xZjqhPXVzphNgoNOHaUVfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: false,
    autoRefreshToken: true,
  }
});